#
# docker-compose-dev.yaml (DEVELOPMENT)
# https://github.com/COSI-Lab/
#
services:
  # --- Log server ---
  log-server:
    build: ./mirrorlog
    container_name: mirrorlog
    expose:
      - 4001
    volumes:
      - "./mirrorlog/logs:/mirror/logs"
      - "./mirrorlog/configs/mirrorlog.conf.json:/mirror/configs/mirrorlog.conf.json:ro"
    networks:
      - mirror
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "1024M"
  
  # --- Sync scheduler ---
  sync-scheduler:
    build: ./mirror-sync-scheduler
    container_name: mirror-sync-scheduler
    volumes:
      - "./mirror-sync-scheduler/storage:/storage"
      - "./mirror-sync-scheduler/configs:/mirror/configs:ro"
      - "./mirror-sync-scheduler/scripts:/mirror/scripts:ro"
    networks:
      - mirror
    depends_on:
      - log-server
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: "16384M"
    stdin_open: true
    tty: true

  # --- Website ---
  website:
    build: ./mirror-website-nuxt
    container_name: mirror-website
    expose:
      - 3000
    volumes:
      - "./configs:/mirror/configs:ro"
    networks:
      - mirror
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8192M"
  
  # --- Metrics engine ---
  metrics:
    build: ./mirror-metrics
    container_name: mirror-metrics
    expose:
      - 8080
    volumes:
      - "./mirror-metrics/access.log:/mirror/access.log:ro"
      - "./mirror-metrics/data:/mirror/data"
    networks:
      - mirror
    depends_on:
      - log-server
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8192M"

  # --- Prometheus DB ---
  prometheus:
    image: prom/prometheus:latest
    container_name: mirror-prometheus
    expose:
      - 9090
    volumes:
      - "./mirror-metrics/configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    networks:
      - mirror
    depends_on:
      - metrics
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: "8192M"

# Lifetime of "mirror" network is not managed by this compose file
networks:
  mirror:
    external: true
