#
# docker-compose-dev.yaml (DEVELOPMENT)
# https://github.com/COSI-Lab/
#
services:
  # --- Website ---
  website:
    build: ./mirror-website
    container_name: mirror-website
    expose:
      - 8000
    networks:
      - mirror
    volumes:
      - "./mirror-website/configs:/home/mirror/configs:ro"

  # --- Website static file server / proxy ---
  website_proxy:
    build:
      context: ./mirror-website
      dockerfile: proxy.Dockerfile
    container_name: mirror-website-proxy
    ports:
      - "127.0.0.1:30301:80"
    networks:
      - mirror
    depends_on:
      - website

  
  # --- Sync scheduler ---
  sync-scheduler:
    build: ./mirror-sync-scheduler
    container_name: mirror-sync-scheduler
    volumes:
      - "./mirror-sync-scheduler/storage:/storage"
      - "./mirror-sync-scheduler/configs:/mirror/configs:ro"
      - "./mirror-sync-scheduler/scripts:/mirror/scripts:ro"
    networks:
      - mirror
    stdin_open: true
    tty: true

  # --- Torrent handler ---
#  torrent-handler:
#    build: ./mirror-torrent-handler
#    container_name: mirror-torrent-handler
#    volumes:
#      - "./mirror-torrent-handler/storage:/storage"
#      - "./mirror-torrent-handler/configs:/mirror/configs:ro"
#    networks:
#      - mirror

  # --- Map ---
#  map:
#    build: ./mirror-map
#    container_name: mirror-map
#    restart: unless-stopped
#    ports:
#      - "30302:8080"
#    networks:
#      - mirror
#    volumes:
#      - "./mirror-map/configs:/mirror/configs:ro"
#      - "./mirror-map/GeoLite2City:/mirror/GeoLite2City"
#    depends_on:
#      - metrics

  # --- Metrics engine ---
  metrics:
    build: ./mirror-metrics
    container_name: mirror-metrics
    expose:
      - 8080
      - 8081
    volumes:
      - "./mirror-metrics/nginx:/mirror/nginx:ro"
      - "metrics:/mirror/data"
    networks:
      - mirror
    depends_on:
      - website

  # --- Prometheus DB ---
  prometheus:
    image: prom/prometheus:latest
    container_name: mirror-prometheus
    expose:
      - 9090
    volumes:
      - "./mirror-metrics/configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    networks:
      - mirror
    depends_on:
      - metrics

networks:
  mirror:
    external: true

volumes:
  metrics: {}
