#
# docker-compose-dev.yaml (DEVELOPMENT)
# https://github.com/COSI-Lab/
#
services:
  # --- Log server ---
  log-server:
    build: ./mirrorlog
    container_name: mirrorlog
    expose:
      - 4001
    volumes:
      - "./mirrorlog/logs:/mirror/logs"
      - "./mirrorlog/configs:/mirror/configs:ro"
    networks:
      - mirror

  # --- Website ---
  api:
    build: ./mirror_website
    container_name: mirror_website
    ports:
      - "30301:8080"
    networks:
      - mirror
    volumes:
      - "./mirror-api/configs:/mirror/configs:ro"
    depends_on:
      - log-server
  
  # --- Sync scheduler ---
  sync-scheduler:
    build: ./mirror-sync-scheduler
    container_name: mirror-sync-scheduler
    volumes:
      - "./mirror-sync-scheduler/storage:/storage"
      - "./mirror-sync-scheduler/configs:/mirror/configs:ro"
      - "./mirror-sync-scheduler/scripts:/mirror/scripts:ro"
    networks:
      - mirror
    depends_on:
      - log-server
    stdin_open: true
    tty: true

  # --- Torrent handler ---
  torrent-handler:
    build: ./mirror-torrent-handler
    container_name: mirror-torrent-handler
    volumes:
      - "./mirror-torrent-handler/storage:/storage"
      - "./mirror-torrent-handler/configs:/mirror/configs:ro"
    networks:
      - mirror
    depends_on:
      - log-server

  # --- Map ---
  map:
    build: ./mirror-map
    container_name: mirror-map
    restart: unless-stopped
    ports:
      - "30302:8080"
    networks:
      - mirror
    volumes:
      - "./mirror-map/configs:/mirror/configs:ro"
      - "./mirror-map/GeoLite2City:/mirror/GeoLite2City"
    depends_on:
      - log-server
      - metrics

  # --- Metrics engine ---
  metrics:
    build: ./mirror-metrics
    container_name: mirror-metrics
    expose:
      - 8080
      - 8081
    volumes:
      - "./mirror-metrics/nginx:/mirror/nginx:ro"
      - "./mirror-metrics/data:/mirror/data"
    networks:
      - mirror
    depends_on:
      - log-server
      - api

  # --- Prometheus DB ---
  prometheus:
    image: prom/prometheus:latest
    container_name: mirror-prometheus
    expose:
      - 9090
    volumes:
      - "./mirror-metrics/configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    networks:
      - mirror
    depends_on:
      - metrics

# Lifetime of "mirror" network is not managed by this compose file
networks:
  mirror:
    external: true
