log_format json_combined escape=json '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"request":"$request",'
    '"status": "$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"http_referer":"$http_referer",'
    '"http_user_agent":"$http_user_agent",'
    '"request_time":"$request_time",'
    '"upstream_response_time":"$upstream_response_time",'
    '"upstream_addr":"$upstream_addr",'
    '"upstream_status":"$upstream_status"'
'}';

access_log /dev/stdout json_combined;

map $request_uri $redirect_uri {
        /index.html /home;
        /distributions.html /projects;
        /distributions /projects;
        /software.html /projects;
        /software /projects;
        /stats.html /stats;
        /history.html /history;
}

server {
    listen [::]:80 default_server;
    listen 80 default_server;

    resolver 127.0.0.11;

    server_name _ ${DNS_BASENAME};

    # Migration from old mirror
    if ( $redirect_uri ) {
            return 301 $redirect_uri;
    }

    # certbot acme challenges
    location /.well_known/acme_challenge {
        root /var/www/.well_known/acme_challenge;
    }

    # wikimedia redirect
    location = /wikimedia {
                return 301 https://wikimedia.${DNS_BASENAME};
    }

    # redirect root to home
    location = / {
        return 301 /home;
    }

    # default location is /storage
    location / {
        root /storage;
        autoindex on;
    }

    # Handle the websocket for the map
    location /ws {
        proxy_pass http://map:8080;
        proxy_http_version 1.1;
	    proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection "upgrade";    
        proxy_set_header Host $host;
    }

    # send website pages to django
    location ~* ^/(home|history|stats|projects|about|map|contact|sync) {
        proxy_pass http://web:8000$uri$is_args$args;
    }

    # Relocation of linuxmint things
    rewrite ^/linuxmint/iso/images/(.*)$ /linuxmint-images/$1 permanent;
    rewrite ^/linuxmint/packages/(.*)$ /linuxmint-packages/$1 permanent;

    # static website resources
    location ^~ /static {
        root /var/www;
    }
}

server {
    listen [::]:80;
    listen 80;

    resolver 127.0.0.11;

    server_name wikimedia.${DNS_BASENAME};
    root /storage/wikimedia;

    # certbot acme challenges
    location /.well_known/acme_challenge {
        root /var/www/.well_known/acme_challenge;
    }

    location /home {
            return 301 /;
    }

    location / {
            index index.html;
    }
}
